// <auto-generated />
using System;
using Concertable.Search.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Concertable.Search.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SearchDbContext))]
    partial class SearchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Concertable.Messaging.Domain.InboxMessageEntity", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConsumerName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageId", "ConsumerName");

                    b.ToTable("Inbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.Messaging.Domain.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset?>("DispatchedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)");

                    b.Property<DateTimeOffset?>("NextRetryAtUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status", "OccurredAtUtc");

                    b.ToTable("Outbox", "messaging", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Concertable.Search.Domain.ReadModels.ArtistRatingProjection", b =>
                {
                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.HasKey("ArtistId");

                    b.ToTable("ArtistRatingProjections", "search");
                });

            modelBuilder.Entity("Concertable.Search.Domain.ReadModels.ArtistReadModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.ToTable("Artists", "search");
                });

            modelBuilder.Entity("Concertable.Search.Domain.ReadModels.ArtistReadModelGenre", b =>
                {
                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<int>("Genre")
                        .HasColumnType("integer");

                    b.HasKey("ArtistId", "Genre");

                    b.ToTable("ArtistGenres", "search");
                });

            modelBuilder.Entity("Concertable.Search.Domain.ReadModels.ConcertRatingProjection", b =>
                {
                    b.Property<int>("ConcertId")
                        .HasColumnType("integer");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.HasKey("ConcertId");

                    b.ToTable("ConcertRatingProjections", "search");
                });

            modelBuilder.Entity("Concertable.Search.Domain.ReadModels.ConcertReadModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<int>("AvailableTickets")
                        .HasColumnType("integer");

                    b.Property<string>("Avatar")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DatePosted")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalTickets")
                        .HasColumnType("integer");

                    b.Property<int>("VenueId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.ToTable("Concerts", "search");
                });

            modelBuilder.Entity("Concertable.Search.Domain.ReadModels.ConcertReadModelGenre", b =>
                {
                    b.Property<int>("ConcertId")
                        .HasColumnType("integer");

                    b.Property<int>("Genre")
                        .HasColumnType("integer");

                    b.HasKey("ConcertId", "Genre");

                    b.ToTable("ConcertGenres", "search");
                });

            modelBuilder.Entity("Concertable.Search.Domain.ReadModels.VenueRatingProjection", b =>
                {
                    b.Property<int>("VenueId")
                        .HasColumnType("integer");

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.HasKey("VenueId");

                    b.ToTable("VenueRatingProjections", "search");
                });

            modelBuilder.Entity("Concertable.Search.Domain.ReadModels.VenueReadModel", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geography (point, 4326)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.ToTable("Venues", "search");
                });

            modelBuilder.Entity("Concertable.Search.Domain.ReadModels.ArtistReadModel", b =>
                {
                    b.OwnsOne("Concertable.Kernel.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("ArtistReadModelId")
                                .HasColumnType("integer");

                            b1.Property<string>("County")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("County");

                            b1.Property<string>("Town")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Town");

                            b1.HasKey("ArtistReadModelId");

                            b1.ToTable("Artists", "search");

                            b1.WithOwner()
                                .HasForeignKey("ArtistReadModelId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.Search.Domain.ReadModels.ArtistReadModelGenre", b =>
                {
                    b.HasOne("Concertable.Search.Domain.ReadModels.ArtistReadModel", "Artist")
                        .WithMany("ArtistGenres")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("Concertable.Search.Domain.ReadModels.ConcertReadModelGenre", b =>
                {
                    b.HasOne("Concertable.Search.Domain.ReadModels.ConcertReadModel", "Concert")
                        .WithMany("ConcertGenres")
                        .HasForeignKey("ConcertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concert");
                });

            modelBuilder.Entity("Concertable.Search.Domain.ReadModels.VenueReadModel", b =>
                {
                    b.OwnsOne("Concertable.Kernel.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("VenueReadModelId")
                                .HasColumnType("integer");

                            b1.Property<string>("County")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("County");

                            b1.Property<string>("Town")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Town");

                            b1.HasKey("VenueReadModelId");

                            b1.ToTable("Venues", "search");

                            b1.WithOwner()
                                .HasForeignKey("VenueReadModelId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Concertable.Search.Domain.ReadModels.ArtistReadModel", b =>
                {
                    b.Navigation("ArtistGenres");
                });

            modelBuilder.Entity("Concertable.Search.Domain.ReadModels.ConcertReadModel", b =>
                {
                    b.Navigation("ConcertGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
