global using Concertable.Shared;
global using Concertable.DataAccess.Infrastructure;
global using Concertable.Search.Application;
global using Concertable.Search.Application.Interfaces;
global using Concertable.Search.Infrastructure.Mappers;
global using ArtistReadModel = Concertable.Search.Domain.Models.ArtistReadModel;
global using ArtistReadModelGenre = Concertable.Search.Domain.Models.ArtistReadModelGenre;
global using VenueReadModel = Concertable.Search.Domain.Models.VenueReadModel;
global using ConcertReadModel = Concertable.Search.Domain.Models.ConcertReadModel;
global using ConcertReadModelGenre = Concertable.Search.Domain.Models.ConcertReadModelGenre;
global using ArtistRatingProjection = Concertable.Search.Domain.Projections.ArtistRatingProjection;
global using VenueRatingProjection = Concertable.Search.Domain.Projections.VenueRatingProjection;
global using ConcertRatingProjection = Concertable.Search.Domain.Projections.ConcertRatingProjection;
global using Concertable.Authorization.Contracts;
global using Concertable.User.Contracts;
global using Concertable.Messaging;
global using Concertable.Messaging.Domain;
